# Generated by Django 3.0.7 on 2024-06-07 09:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_auto_20240603_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='session_year_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.SessionYearModel'),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.Subjects'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 7, 14, 33, 16, 293661)),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 7, 14, 33, 16, 293661)),
        ),
    ]
