# Generated by Django 3.0.7 on 2024-06-10 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_auto_20240607_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 11, 4, 44, 647282)),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 11, 4, 44, 647282)),
        ),
    ]
