# Generated by Django 3.0.7 on 2024-06-13 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_auto_20240610_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 12, 20, 29, 301027)),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 12, 20, 29, 301027)),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
