# Generated by Django 5.0.6 on 2024-06-15 10:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_alter_attendance_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 10, 37, 51, 508548)),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 10, 37, 51, 508548)),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.students'),
        ),
    ]
