# Generated by Django 5.0.6 on 2024-06-15 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_alter_attendance_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 11, 42, 36, 200777)),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 11, 42, 36, 216443)),
        ),
    ]
